# Use the official Python 3 image as the base image
ARG VARIANT=3.12-bullseye
from mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}

# Install Python packages
RUN pip install pandas pdfplumber
